// Danh sách môn học THPT cố định
// icon_name: tên component từ thư viện lucide-react
export const SUBJECTS = [
  {
    id: 'toan',
    name: 'Toán học',
    description: 'Đại số, Giải tích, Hình học không gian và các chuyên đề Toán THPT',
    icon_name: 'Calculator',
    bg_class: 'bg-blue-50',
    color_class: 'text-blue-600',
  },
  {
    id: 'ngu-van',
    name: 'Ngữ văn',
    description: 'Văn học Việt Nam, Nghị luận xã hội và Nghị luận văn học',
    icon_name: 'BookOpen',
    bg_class: 'bg-purple-50',
    color_class: 'text-purple-600',
  },
  {
    id: 'tieng-anh',
    name: 'Tiếng Anh',
    description: 'Ngữ pháp, Từ vựng, Đọc hiểu và Kỹ năng giao tiếp tiếng Anh',
    icon_name: 'Globe',
    bg_class: 'bg-green-50',
    color_class: 'text-green-600',
  },
  {
    id: 'vat-ly',
    name: 'Vật lý',
    description: 'Cơ học, Điện học, Quang học và Vật lý hạt nhân',
    icon_name: 'Zap',
    bg_class: 'bg-yellow-50',
    color_class: 'text-yellow-600',
  },
  {
    id: 'hoa-hoc',
    name: 'Hóa học',
    description: 'Hóa vô cơ, Hóa hữu cơ và Hóa đại cương',
    icon_name: 'FlaskConical',
    bg_class: 'bg-orange-50',
    color_class: 'text-orange-600',
  },
  {
    id: 'sinh-hoc',
    name: 'Sinh học',
    description: 'Di truyền học, Sinh thái học và Sinh học tế bào',
    icon_name: 'Leaf',
    bg_class: 'bg-emerald-50',
    color_class: 'text-emerald-600',
  },
  {
    id: 'lich-su',
    name: 'Lịch sử',
    description: 'Lịch sử Việt Nam và Lịch sử thế giới hiện đại',
    icon_name: 'Landmark',
    bg_class: 'bg-amber-50',
    color_class: 'text-amber-700',
  },
  {
    id: 'dia-ly',
    name: 'Địa lý',
    description: 'Địa lý tự nhiên, Địa lý kinh tế - xã hội Việt Nam và thế giới',
    icon_name: 'Map',
    bg_class: 'bg-teal-50',
    color_class: 'text-teal-600',
  },
  {
    id: 'gdcd',
    name: 'Giáo dục công dân',
    description: 'Pháp luật, Đạo đức và Kinh tế - chính trị trong chương trình THPT',
    icon_name: 'Scale',
    bg_class: 'bg-indigo-50',
    color_class: 'text-indigo-600',
  },
];
